### ISSUE TITLE
Respond to question through Answer form

### ISSUE THREAD

**Issue by CampbellBrett** [UVProtocol/www#6]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- I checked the documentation and found no answer.
- I checked to make sure that this issue has not already been filed.
- I'm reporting the issue to the correct repository (for multi-repository projects).
- I've read the [CONTRIBUTING](https://github.com/HackCapital/cto.ai/blob/master/.github/CONTRIBUTING.md) document.
- If it is SRED eligible, I've added the label SRED.
- I've named a clear and solution focused title.

# Overview

We need an Admin interface for submitting answers to questions

# Expected Behavior

As an Admin I can respond to a question. It should be stored in postgres.

# Current Behavior

Currently we can only answer a question through cURL

# Tasks
- [ ] Create Answer form component
- [ ] Create component Submission method to handle right the answer to postgres
- [ ] Write tests insure functionality

# Additional Notes

(This is an optional section)
Use this sections to **add notes, reference other related issues/PR, or data such as benchmarks**

# Failure Case

**If it is not a bug, please remove the rest of this template.**
Please help provide information about the failure if this is a bug.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Step 1
2. Step 2
3. You get it...

## Context

Please provide any relevant information about your setup, **if relevant**.
This is important in case the issue is not reproducible except for under certain conditions.
Example: Operating System, Operating System version, and Runtime (NodeJS/Go/Rust) version.

## Logs

If any, please include relevant log snippets or files here.
